2024-08-26 09:34:56,412 [INFO] [main.py:20 - <module>()] 


Start Prototype UI webapp! 

2024-08-26 09:34:56,804 [INFO] [main.py:20 - <module>()] 


Start Prototype UI webapp! 

2024-08-26 09:34:56,845 [INFO] [main.py:20 - <module>()] 


Start Prototype UI webapp! 

2024-08-26 09:37:14,409 [INFO] [item.py:15 - read_items()] Request get items:
2024-08-26 09:37:14,417 [ERROR] [item.py:24 - read_items()] DB Exception: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 2223 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-08-26 09:37:14,417 [INFO] [item.py:17 - read_items()] Response: response=[Exception] "AppExceptionCase"
2024-08-26 09:39:48,377 [INFO] [main.py:20 - <module>()] 


Start Prototype UI webapp! 

2024-08-26 09:39:48,713 [INFO] [main.py:20 - <module>()] 


Start Prototype UI webapp! 

2024-08-26 09:39:48,723 [INFO] [main.py:20 - <module>()] 


Start Prototype UI webapp! 

2024-08-26 09:40:01,384 [INFO] [item.py:15 - read_items()] Request get items:
2024-08-26 09:40:01,422 [INFO] [item.py:17 - read_items()] Response: response=[Success]
